baseurl: 'https://school.brainhackmtl.org'
title: 'BrainHack School'
theme: hugo-universal-theme
defaultContentLanguage: en
defaultContentLanguageInSubdir: FALSE

outputFormats:
  Calendar:
    mediaType: text/calendar

languages:
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    weight: 1
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: Schedule
          name: Schedule
          url: /schedule/
          weight: 2
        - identifier: Weeks
          name: Weeks
          url: /weeks/
          weight: 2
        - identifier: Locations
          name: Locations
          url: /locations/
          weight: 3
        - identifier: Register
          name: Register
          url: /register/
          weight: 4
        - identifier: documents
          name: Documents
          weight: 6
          url: /guide/
        - parent: documents
          name: Installation
          url: /setup/
          weight: 7
        - parent: documents
          name: Getting started
          url: /guide/
          weight: 8
        - parent: documents
          name: Code of Conduct
          url: /coc/
          weight: 9
        - parent: documents
          name: Projects
          url: /project_guide
          weight: 9

      topbar:
        - weight: 1
          name: GitHub
          url: 'https://github.com/brainhackMTL/school/'
          pre: <i class='fab fa-2x fa-github'></i>
        - weight: 3
          name: Twitter
          url: 'http://twitter.com/brainhackMTL'
          pre: <i class='fab fa-2x fa-twitter'></i>
        - weight: 4
          name: Email
          url: 'mailto:emilie.dessureault@criugm.qc.ca'
          pre: <i class='fas fa-2x fa-envelope'></i>

    params:
      outputFormats:
        Calendar:
          mediaType: text/calendar
      viewMorePostLink: /blog/
      author: BHS
      defaultKeywords:
        - BrainHack
        - Neuroscience
      mainSections:
        - blog
      defaultDescription: Brainhack School
      facebook_site: ''
      twitter_site: BrainhackMTL
      default_sharing_image: img/brainhackSchool.jpg
      googleMapsApiKey:
      style: green
      email:
      contact_form_ajax: false
      about_us: >-
        <p>Fundamentals and project in neural data science.</p>
      copyright: 'Copyright (c) 2020, BrainHack School; all rights reserved.'
      date_format: 'January 2, 2006'
      logo: img/logo_brainhack.png
      logo_small: img/logo-small.png
      address: |-
        <p class="text-uppercase"><strong>BrainHack School</strong>
                <br>
                <br>Montreal
                <br>
                <strong>Canada</strong>
              </p>

      latitude: '45.50884'
      longitude: '-73.58781'

      widgets:
        categories: true
        tags: true
        search: true
      carousel:
        enable: true
      instructors:
        enable: true
      features:
        enable: false
      testimonials:
        enable: true
        title: Why Brainhack School?
        subtitle: >-
          Coding and other data science skills are much better acquired and
          solidified through practice. After a one week bootcamp, most of the
          brainhack training consists of open and collaborative work on a project of
          your choice.
      see_more:
        enable: true
        icon: far fa-file-alt
        title: 'Project-based, transdisciplinary training'
        subtitle: 'Neuroscience, Statistical Modelling and Computer Science'
        link_url: /register
        link_text: "Registration may be closed for this year, but you can watch the lectures"
        video: https://www.youtube.com/embed/PTYs_JFKsHI?list=PLfqBzCl5BL3-m9BH5qi4u4QzoJBC8Ze72
      clients:
        enable: true
        title: Partner institutions
        subtitle: ''
      recent_posts:
        enable: false
        title: Project gallery
        subtitle: A selection of projects from our students
      topbar:
        enable: true
        text: "**:computer: :brain: [Registrations](/register) are now closed. :brain: :computer:** :house: Due to the [COVID-19](https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec/) pandemic, this year will be entirely virtual! :film_projector: "


  fr:
    languageCode: fr
    languageName: Français
    contentDir: content/fr
    title: 'École BrainHack'
    weight: 2
    menu:
      main:
        - identifier: home
          name: Accueil
          url: /
          weight: 1
        - identifier: Schedule
          name: Horaire
          url: /schedule/
          weight: 2
        - identifier: Weeks
          name: Semaines
          url: /weeks/
          weight: 2
        - identifier: Locations
          name: Sites
          url: /locations/
          weight: 3
        - identifier: Register
          name: S'inscrire
          url: /register/
          weight: 4
        - identifier: documents
          name: Documents
          weight: 6
          url: /guide/

        - parent: documents
          name: Getting started Guide
          url: /fr/guide/
          weight: 7

        - parent: documents
          name: Code de conduite
          url: /coc/
          weight: 8
      topbar:
        - weight: 1
          name: GitHub
          url: 'https://github.com/brainhackMTL/school/'
          pre: <i class='fab fa-2x fa-github'></i>
        - weight: 3
          name: Twitter
          url: 'http://twitter.com/brainhackMTL'
          pre: <i class='fab fa-2x fa-twitter'></i>
        - weight: 4
          name: Email
          url: 'mailto:info@bhs.com'
          pre: <i class='fas fa-2x fa-envelope'></i>

    params:
      viewMorePostLink: /blog/
      author: BHS
      defaultKeywords:
        - BrainHack
        - Neuroscience
      mainSections:
        - blog
      defaultDescription:
      facebook_site: ''
      twitter_site: BrainhackMTL
      default_sharing_image: img/sharing-default.png
      googleMapsApiKey:
      style: green
      email: your@email.com
      contact_form_ajax: false
      about_us: >-
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
        fames ac turpis egestas.</p>
      copyright: 'Copyright (c) 2020, BrainHack School; all rights reserved.'
      date_format: 'January 2, 2006'
      logo: img/logo_brainhack.png
      logo_small: img/logo-small.png
      address: |-
        <p class="text-uppercase"><strong>BrainHack School</strong>
                <br>
                <br>Montreal
                <br>
                <strong>Canada</strong>
              </p>

      latitude: '45.50884'
      longitude: '-73.58781'

      widgets:
        categories: true
        tags: true
        search: true
      carousel:
        enable: true
      instructors:
        enable: true
      features:
        enable: false
      testimonials:
        enable: true
        title: Pourquoi Brainhack School?
        subtitle: >-
          L'apprentissage par la pratique est très bien adapté pour la programmation et les autres compétences utiles en sciences des données. Après une semaine intensive de présentations,
          la majorité de la formation Brainhack consiste en un projet de votre choix, réalisé de votre de manière ouverte et collaborative.
      see_more:
        enable: true
        icon: far fa-file-alt
        title: 'Formation transdisciplinaire axée sur les projets'
        subtitle: 'Neurosciences, Modélisation statistique et Sciences informatiques'
        link_url: /register
        link_text: Inscrivez-vous maintenant
      clients:
        enable: true
        title: Institutions partenaires
        subtitle: ''
      recent_posts:
        enable: false
        title: Project gallery
        subtitle: A selection of projects from our students
      topbar:
        enable: true
        text: "**:computer: :brain: Les [inscriptions](/register) sont maintenant fermées. :brain: :computer:** :house: Face à la pandémie de [COVID-19](https://www.quebec.ca/sante/problemes-de-sante/a-z/coronavirus-2019/situation-coronavirus-quebec/), l'école sera virtuelle cette année! :film_projector: "

Permalinks:
  blog: '/blog/:year/:month/:day/:filename/'

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3


disqusShortname: ''
googleAnalytics: ''
paginate: 10
